/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateOriginArgs } from "./CreateOriginArgs";
import { UpdateOriginArgs } from "./UpdateOriginArgs";
import { DeleteOriginArgs } from "./DeleteOriginArgs";
import { OriginFindManyArgs } from "./OriginFindManyArgs";
import { OriginFindUniqueArgs } from "./OriginFindUniqueArgs";
import { Origin } from "./Origin";
import { SongFindManyArgs } from "../../song/base/SongFindManyArgs";
import { Song } from "../../song/base/Song";
import { OriginService } from "../origin.service";

@graphql.Resolver(() => Origin)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class OriginResolverBase {
  constructor(
    protected readonly service: OriginService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Origin",
    action: "read",
    possession: "any",
  })
  async _originsMeta(
    @graphql.Args() args: OriginFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Origin])
  @nestAccessControl.UseRoles({
    resource: "Origin",
    action: "read",
    possession: "any",
  })
  async origins(@graphql.Args() args: OriginFindManyArgs): Promise<Origin[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Origin, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Origin",
    action: "read",
    possession: "own",
  })
  async origin(
    @graphql.Args() args: OriginFindUniqueArgs
  ): Promise<Origin | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Origin)
  @nestAccessControl.UseRoles({
    resource: "Origin",
    action: "create",
    possession: "any",
  })
  async createOrigin(@graphql.Args() args: CreateOriginArgs): Promise<Origin> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Origin)
  @nestAccessControl.UseRoles({
    resource: "Origin",
    action: "update",
    possession: "any",
  })
  async updateOrigin(
    @graphql.Args() args: UpdateOriginArgs
  ): Promise<Origin | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Origin)
  @nestAccessControl.UseRoles({
    resource: "Origin",
    action: "delete",
    possession: "any",
  })
  async deleteOrigin(
    @graphql.Args() args: DeleteOriginArgs
  ): Promise<Origin | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Song])
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "read",
    possession: "any",
  })
  async songs(
    @graphql.Parent() parent: Origin,
    @graphql.Args() args: SongFindManyArgs
  ): Promise<Song[]> {
    const results = await this.service.findSongs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
