/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SongService } from "../song.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SongCreateInput } from "./SongCreateInput";
import { SongWhereInput } from "./SongWhereInput";
import { SongWhereUniqueInput } from "./SongWhereUniqueInput";
import { SongFindManyArgs } from "./SongFindManyArgs";
import { SongUpdateInput } from "./SongUpdateInput";
import { Song } from "./Song";
import { AlbumFindManyArgs } from "../../album/base/AlbumFindManyArgs";
import { Album } from "../../album/base/Album";
import { AlbumWhereUniqueInput } from "../../album/base/AlbumWhereUniqueInput";
import { ArtistFindManyArgs } from "../../artist/base/ArtistFindManyArgs";
import { Artist } from "../../artist/base/Artist";
import { ArtistWhereUniqueInput } from "../../artist/base/ArtistWhereUniqueInput";
import { PlaylistFindManyArgs } from "../../playlist/base/PlaylistFindManyArgs";
import { Playlist } from "../../playlist/base/Playlist";
import { PlaylistWhereUniqueInput } from "../../playlist/base/PlaylistWhereUniqueInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SongControllerBase {
  constructor(
    protected readonly service: SongService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Song })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: SongCreateInput): Promise<Song> {
    return await this.service.create({
      data: {
        ...data,

        origin: data.origin
          ? {
              connect: data.origin,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        origin: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Song] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(SongFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Song[]> {
    const args = plainToClass(SongFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        origin: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Song })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: SongWhereUniqueInput
  ): Promise<Song | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        origin: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Song })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() data: SongUpdateInput
  ): Promise<Song | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          origin: data.origin
            ? {
                connect: data.origin,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          origin: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Song })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: SongWhereUniqueInput
  ): Promise<Song | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          origin: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/album")
  @ApiNestedQuery(AlbumFindManyArgs)
  async findManyAlbum(
    @common.Req() request: Request,
    @common.Param() params: SongWhereUniqueInput
  ): Promise<Album[]> {
    const query = plainToClass(AlbumFindManyArgs, request.query);
    const results = await this.service.findAlbum(params.id, {
      ...query,
      select: {
        artist: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        imagePath: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/album")
  async connectAlbum(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: AlbumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      album: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/album")
  async updateAlbum(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: AlbumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      album: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/album")
  async disconnectAlbum(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: AlbumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      album: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Artist",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/artist")
  @ApiNestedQuery(ArtistFindManyArgs)
  async findManyArtist(
    @common.Req() request: Request,
    @common.Param() params: SongWhereUniqueInput
  ): Promise<Artist[]> {
    const query = plainToClass(ArtistFindManyArgs, request.query);
    const results = await this.service.findArtist(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        imagePath: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/artist")
  async connectArtist(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: ArtistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      artist: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/artist")
  async updateArtist(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: ArtistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      artist: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/artist")
  async disconnectArtist(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: ArtistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      artist: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Playlist",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/inPlaylist")
  @ApiNestedQuery(PlaylistFindManyArgs)
  async findManyInPlaylist(
    @common.Req() request: Request,
    @common.Param() params: SongWhereUniqueInput
  ): Promise<Playlist[]> {
    const query = plainToClass(PlaylistFindManyArgs, request.query);
    const results = await this.service.findInPlaylist(params.id, {
      ...query,
      select: {
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/inPlaylist")
  async connectInPlaylist(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: PlaylistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inPlaylist: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/inPlaylist")
  async updateInPlaylist(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: PlaylistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inPlaylist: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/inPlaylist")
  async disconnectInPlaylist(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: PlaylistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inPlaylist: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/likedBy")
  @ApiNestedQuery(UserFindManyArgs)
  async findManyLikedBy(
    @common.Req() request: Request,
    @common.Param() params: SongWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findLikedBy(params.id, {
      ...query,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/likedBy")
  async connectLikedBy(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      likedBy: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/likedBy")
  async updateLikedBy(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      likedBy: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/likedBy")
  async disconnectLikedBy(
    @common.Param() params: SongWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      likedBy: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
