/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AlbumUpdateManyWithoutSongsInput } from "./AlbumUpdateManyWithoutSongsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ArtistUpdateManyWithoutSongsInput } from "./ArtistUpdateManyWithoutSongsInput";
import { PlaylistUpdateManyWithoutSongsInput } from "./PlaylistUpdateManyWithoutSongsInput";
import { UserUpdateManyWithoutSongsInput } from "./UserUpdateManyWithoutSongsInput";
import { OriginWhereUniqueInput } from "../../origin/base/OriginWhereUniqueInput";
@InputType()
class SongUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AlbumUpdateManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => AlbumUpdateManyWithoutSongsInput)
  @IsOptional()
  @Field(() => AlbumUpdateManyWithoutSongsInput, {
    nullable: true,
  })
  album?: AlbumUpdateManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => ArtistUpdateManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => ArtistUpdateManyWithoutSongsInput)
  @IsOptional()
  @Field(() => ArtistUpdateManyWithoutSongsInput, {
    nullable: true,
  })
  artist?: ArtistUpdateManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => PlaylistUpdateManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => PlaylistUpdateManyWithoutSongsInput)
  @IsOptional()
  @Field(() => PlaylistUpdateManyWithoutSongsInput, {
    nullable: true,
  })
  inPlaylist?: PlaylistUpdateManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutSongsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutSongsInput, {
    nullable: true,
  })
  likedBy?: UserUpdateManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => OriginWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OriginWhereUniqueInput)
  @IsOptional()
  @Field(() => OriginWhereUniqueInput, {
    nullable: true,
  })
  origin?: OriginWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { SongUpdateInput };
