/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AlbumCreateNestedManyWithoutSongsInput } from "./AlbumCreateNestedManyWithoutSongsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ArtistCreateNestedManyWithoutSongsInput } from "./ArtistCreateNestedManyWithoutSongsInput";
import { OriginCreateNestedManyWithoutSongsInput } from "./OriginCreateNestedManyWithoutSongsInput";
import { PlaylistWhereUniqueInput } from "../../playlist/base/PlaylistWhereUniqueInput";
@InputType()
class SongCreateInput {
  @ApiProperty({
    required: false,
    type: () => AlbumCreateNestedManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => AlbumCreateNestedManyWithoutSongsInput)
  @IsOptional()
  @Field(() => AlbumCreateNestedManyWithoutSongsInput, {
    nullable: true,
  })
  album?: AlbumCreateNestedManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => ArtistCreateNestedManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => ArtistCreateNestedManyWithoutSongsInput)
  @IsOptional()
  @Field(() => ArtistCreateNestedManyWithoutSongsInput, {
    nullable: true,
  })
  artist?: ArtistCreateNestedManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => OriginCreateNestedManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => OriginCreateNestedManyWithoutSongsInput)
  @IsOptional()
  @Field(() => OriginCreateNestedManyWithoutSongsInput, {
    nullable: true,
  })
  origin?: OriginCreateNestedManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => PlaylistWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlaylistWhereUniqueInput)
  @IsOptional()
  @Field(() => PlaylistWhereUniqueInput, {
    nullable: true,
  })
  playlist?: PlaylistWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { SongCreateInput };
