/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSongArgs } from "./CreateSongArgs";
import { UpdateSongArgs } from "./UpdateSongArgs";
import { DeleteSongArgs } from "./DeleteSongArgs";
import { SongFindManyArgs } from "./SongFindManyArgs";
import { SongFindUniqueArgs } from "./SongFindUniqueArgs";
import { Song } from "./Song";
import { AlbumFindManyArgs } from "../../album/base/AlbumFindManyArgs";
import { Album } from "../../album/base/Album";
import { ArtistFindManyArgs } from "../../artist/base/ArtistFindManyArgs";
import { Artist } from "../../artist/base/Artist";
import { OriginFindManyArgs } from "../../origin/base/OriginFindManyArgs";
import { Origin } from "../../origin/base/Origin";
import { Playlist } from "../../playlist/base/Playlist";
import { SongService } from "../song.service";

@graphql.Resolver(() => Song)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SongResolverBase {
  constructor(
    protected readonly service: SongService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "read",
    possession: "any",
  })
  async _songsMeta(
    @graphql.Args() args: SongFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Song])
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "read",
    possession: "any",
  })
  async songs(@graphql.Args() args: SongFindManyArgs): Promise<Song[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Song, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "read",
    possession: "own",
  })
  async song(@graphql.Args() args: SongFindUniqueArgs): Promise<Song | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Song)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "create",
    possession: "any",
  })
  async createSong(@graphql.Args() args: CreateSongArgs): Promise<Song> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        playlist: args.data.playlist
          ? {
              connect: args.data.playlist,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Song)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "update",
    possession: "any",
  })
  async updateSong(@graphql.Args() args: UpdateSongArgs): Promise<Song | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          playlist: args.data.playlist
            ? {
                connect: args.data.playlist,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Song)
  @nestAccessControl.UseRoles({
    resource: "Song",
    action: "delete",
    possession: "any",
  })
  async deleteSong(@graphql.Args() args: DeleteSongArgs): Promise<Song | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Album])
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "read",
    possession: "any",
  })
  async album(
    @graphql.Parent() parent: Song,
    @graphql.Args() args: AlbumFindManyArgs
  ): Promise<Album[]> {
    const results = await this.service.findAlbum(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Artist])
  @nestAccessControl.UseRoles({
    resource: "Artist",
    action: "read",
    possession: "any",
  })
  async artist(
    @graphql.Parent() parent: Song,
    @graphql.Args() args: ArtistFindManyArgs
  ): Promise<Artist[]> {
    const results = await this.service.findArtist(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Origin])
  @nestAccessControl.UseRoles({
    resource: "Origin",
    action: "read",
    possession: "any",
  })
  async origin(
    @graphql.Parent() parent: Song,
    @graphql.Args() args: OriginFindManyArgs
  ): Promise<Origin[]> {
    const results = await this.service.findOrigin(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Playlist, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Playlist",
    action: "read",
    possession: "any",
  })
  async playlist(@graphql.Parent() parent: Song): Promise<Playlist | null> {
    const result = await this.service.getPlaylist(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
