/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AlbumUpdateManyWithoutSongsInput } from "./AlbumUpdateManyWithoutSongsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ArtistUpdateManyWithoutSongsInput } from "./ArtistUpdateManyWithoutSongsInput";
import { OriginUpdateManyWithoutSongsInput } from "./OriginUpdateManyWithoutSongsInput";
import { PlaylistWhereUniqueInput } from "../../playlist/base/PlaylistWhereUniqueInput";
@InputType()
class SongUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AlbumUpdateManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => AlbumUpdateManyWithoutSongsInput)
  @IsOptional()
  @Field(() => AlbumUpdateManyWithoutSongsInput, {
    nullable: true,
  })
  album?: AlbumUpdateManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => ArtistUpdateManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => ArtistUpdateManyWithoutSongsInput)
  @IsOptional()
  @Field(() => ArtistUpdateManyWithoutSongsInput, {
    nullable: true,
  })
  artist?: ArtistUpdateManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => OriginUpdateManyWithoutSongsInput,
  })
  @ValidateNested()
  @Type(() => OriginUpdateManyWithoutSongsInput)
  @IsOptional()
  @Field(() => OriginUpdateManyWithoutSongsInput, {
    nullable: true,
  })
  origin?: OriginUpdateManyWithoutSongsInput;

  @ApiProperty({
    required: false,
    type: () => PlaylistWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlaylistWhereUniqueInput)
  @IsOptional()
  @Field(() => PlaylistWhereUniqueInput, {
    nullable: true,
  })
  playlist?: PlaylistWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { SongUpdateInput };
